// Generated by typings
// Source: definitions/index.d.ts
declare module 'non-memory-map' {
export interface IMapOptions {
    path: string;
    mapSize: number;
    maxDbs?: number;
}
export interface IDatabase {
    env?: any;
    data?: any;
    types?: any;
    pointer?: number;
    txn?: any;
    txns?: number;
}
export class NonMemoryMap {
    private options;
    private db;
    private id;
    constructor(options: IMapOptions, db?: IDatabase, id?: number);
    private getKeyID(key);
    beginTransaction(): any;
    commit(): void;
    abort(): void;
    private debug(operation, isData, key, value?);
    private getString(db, key);
    private getNumber(db, key);
    private getBoolean(db, key);
    private putString(db, key, value);
    private putNumber(db, key, value);
    private putBoolean(db, key, value);
    get(key: string): any;
    set(key: string, value: (string | number | boolean | Object)): void;
    private getObject(key);
    private setObject(key, object);
    toString(): string;
}
}
